/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function publicKey(seed: Uint8Array): Buffer
export declare function ringVrfOutputHash(signature: Uint8Array): Buffer
export declare function ringVrfVerify(signature: Uint8Array, vrfInputData: Uint8Array, auxData: Uint8Array, commitment: Buffer, ringSize: number): boolean
export declare function ringRoot(input: Uint8Array): Buffer
/**
 * Generates `Y` without signatur
*/
export declare function ietfVrfOutputHashFromSecret(seed: Uint8Array, vrfInputData: Uint8Array): Buffer
/**
 * G.1
 * sign
*/
export declare function ietfVrfSign(seed: Uint8Array, vrfInputData: Uint8Array, auxData: Uint8Array): Buffer
/**
 * G.1
 * verify signature with given pubkey
*/
export declare function ietfVrfVerify(publicKey: Uint8Array, vrfInputData: Uint8Array, auxData: Uint8Array, signature: Uint8Array): boolean
export declare function ietfVrfOutputHash(signature: Uint8Array): Buffer
