/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function vrfOutputHash(signature: Uint8Array): Buffer
export declare function vrfVerify(signature: Uint8Array, vrfInputData: Uint8Array, auxData: Uint8Array, commitment: Buffer, ringSize: number): boolean
export declare function ringRoot(input: Uint8Array): Buffer
